# Generated by Django 6.0.6 on 2026-07-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(help_text='ID ya kazi kutoka jobs service')),
                ('freelancer_id', models.IntegerField(help_text='ID ya mwanafunzi/freelancer kutoka accounts service')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposal', models.TextField(help_text='Eleza kwanini wewe unafaa kwa kazi hii')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
