# Generated by Django 6.0.6 on 2026-07-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField(help_text='ID ya anayetoa review kutoka accounts service')),
                ('reviewee_id', models.IntegerField(help_text='ID ya anayepokea review kutoka accounts service')),
                ('job_id', models.IntegerField(help_text='ID ya kazi husika kutoka jobs service')),
                ('rating', models.PositiveSmallIntegerField(help_text='Weka nyota 1 hadi 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
